import { Button } from '@/components/ui/button';
import { Download } from 'lucide-react';
import { StoryResult } from '@/lib/generate-story';

interface DownloadPDFProps {
  story: StoryResult;
}

export default function DownloadPDF({ story }: DownloadPDFProps) {
  const handleDownload = () => {
    const content = `
${story.title}
${'='.repeat(story.title.length)}

${story.story}

${story.moral ? `\nMoral: ${story.moral}` : ''}

---
Generated by StoryForge
    `.trim();

    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${story.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <Button onClick={handleDownload} variant="outline" size="sm">
      <Download className="mr-2 h-4 w-4" />
      Download
    </Button>
  );
}